In [4]:
# example #1:python---3 p t o
#                  ---3 y h n
# output:programming
# function return output as "samecount"or"programming"

def findCharCount(s):
    cntupper=0
    cntlower=0
    for i in range(len(s)):
        if ord(s[i]) >=65 and ord(s[i]) <=90:
            cntupper+=1
        elif ord(s[i]) >=97 and ord(s[i]) <=122:
            cntlower+=1
    if cntlower==cntupper:
        return"sameCount"
    return "programming"
findCharCount('PyThoN')

'sameCount'

In [6]:
# function to extract the digits from the string
# example #1:
# input :Appli18cation89
# output :1 8 8 9



def digitString(n):
    for i in range(len(n)):
        if ord(n[i]) >=48 and ord(n[i]) <=57:
            print(n[i],end=' ')
    return
digitString('Appli18cation89')
            
        

1 8 8 9 

In [17]:
# function to add the digit of the string
# example #1
# input : Appli18cation89
# output: 26(1+8+8+9)


def addDigitString(s):
    c=0
    for i in range(len(s)):
        if ord(s[i]) >=48 and ord(s[i]) <=57:
            c=c+(ord(s[i])-48)
            print(s[i],end=' ')
    return c
addDigitString('Appli18cation89')

1 8 8 9 

26

In [22]:
# function is specific word in upper case
# example #1:
# input : Python Made Easy
# output : MADE
# example #2:
# input : Learn Python Stings
# output : PYTHON
def wordUpper(s):
    cntSpace = 0
    for i in range(len(s)):
        if ord(s[i]) == 32:
            cntSpace+=1
        if cntSpace==1:
            if ord(s[i]) >=65 and ord(s[i]) <=90:
                print(s[i],end=' ')
            elif ord(s[i]) >=97 and ord(s[i]) <=122:
                print(chr(ord(s[i])-32),end=' ')
        if cntSpace==2:
            break
    return        
wordUpper('Python Made Easy')# MADE            
        

M A D E 

In [18]:
ord('a')

97

In [19]:
ord('z')

122

In [20]:
ord('A')

65

In [21]:
ord('Z')

90

In [43]:
# function to print upper case character
# ascii
#A-Z:65-90
#a-z:97-122
#0-9:48-57
#space:32
def printUpper(s):
    for i in range(len(s)):
        if ord(s[i]) >=65 and ord(s[i]) <=90:
            print(s[i],end=' ')
    return
printUpper('PyThoN')

P T N 

In [49]:
def reverse(s):
    return s[::-1]
reverse('python')

'nohtyp'

In [ ]:
def palindrome(s):
    if 

### List
-one of the data structure in python
-data structure means to store,sort and search option
-its one common data structure in python,iteams of list seperated by comma enclosed in square brackets[]
    .Example
        .l=[1,2,3,4,5]
        .l2=['gitam',1,2,3,'vizag']


In [31]:
l=[1,2,3,4,5]
print(l)
print(l[0])
print(l[1])
print(l[-1])
print(l[0:1])
print(l[2:])
print(l[2:4])
print(l[-2:4])
print(l[ :2])

[1, 2, 3, 4, 5]
1
2
5
[1]
[3, 4, 5]
[3, 4]
[4]
[1, 2]


In [33]:
li =["gitam",1582,2018,2019,"vizag"]
print(li)
li[1]=1234
print(li)

['gitam', 1582, 2018, 2019, 'vizag']
['gitam', 1234, 2018, 2019, 'vizag']


In [34]:
# delete the list items from the list
del li[3]
print(li)

['gitam', 1234, 2018, 'vizag']


In [39]:
# basic list operations
li =[1,2,3,4,5]
#len of the list
print(len(li))
#list repitation
print(li*2)
#to know certain item is present in the list or not
print(4 in li)
print(10 in li)
#acess the list items from the iteration 
#1 way to define
for i in range(len(li)):
    print(li[i],end=' ')
print()
#2 way to print the list items
for i in li:
    print(i,end=' ')

5
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
True
False
1 2 3 4 5 
1 2 3 4 5 

In [42]:
# basic list functions
li=[1,9,16,25,5]
print(max(li))# max of list
print(min(li))# min of list
print(sum(li))# sum of list
print(sum(li)//len(li))# average of list

25
1
56
11


In [57]:
# methods of list
li=[1,9,16,25,5]
li.append(6)
#li.index(2,56)
li.append(9)
li.count(9)
#li.index(56)
print(li)

[1, 9, 16, 25, 5, 6, 9]


In [59]:
li.sort()
print(li)

[1, 5, 6, 9, 9, 16, 25]


In [66]:
li.pop(1)
print(li)

[1, 56, 56, 6, 9, 9, 16]


In [63]:
li.index(5)

1

In [65]:
li.insert(2,56)
print(li)

[1, 5, 56, 56, 6, 9, 9, 16]


In [72]:
l=[1,6,19,25]
l.extend(li)
l.reverse()
l.sort()
print(l)

[1, 1, 6, 6, 9, 9, 16, 19, 25, 56, 56]


In [73]:
def largeNumber(li):
    li.sort()
    return li[-1]
def genericLarge(li,n):
    li.sort()
    return li[-n]
li=[19,1,25,6,9,45,22]
print(largeNumber(li))
print(genericLarge(li,3))# third large

45
22


In [74]:
# function to find least and generic least number of list
def leastNumber(li):
    li.sort()
    return li[0]
def genericLeast(li,n):
    li.sort()
    return li[n-1]
li=[19,1,25,6,9,45,22]
print(leastNumber(li))
print(genericLeast(li,3))# third least

1
9


# File Handling in python
    .file-document which contains some information and resides on permananent

In [76]:
def createFile(filename):
    f = open(filename,'w')
    for i in range(10):
        f.write('This is %d Line \n'%i)
    print('file is sucessfully created data has inserted')
    return
createFile('data.txt')

file is sucessfully created data has inserted


In [90]:
#Mode --a()
# -- if the file is already present with same name


def appendMode(filename):
    f = open(filename,'a')
    f.write('gitam vizag\n')
    f.write('Python Programming\n')
    print('program completed sucessfully')
    return
appendMode('data.txt')

SyntaxError: 'return' outside function (<ipython-input-90-af759a249307>, line 10)

In [79]:
# Function to red the file
def readFileData(filename):
    f = open(filename,'r')
    if f.mode=='r':
        a = f.read()
        print(a)
    f.close()
    return
readFileData('data.txt')

This is 0 Line 
This is 1 Line 
This is 2 Line 
This is 3 Line 
This is 4 Line 
This is 5 Line 
This is 6 Line 
This is 7 Line 
This is 8 Line 
This is 9 Line 



In [ ]:
# analysis on the file--word count,char count,digit count

In [81]:
# word count -- input file
def wordCount(filename):
    with open(filename,'r')as f:
        if f.mode == 'r':
            a = f.read()
            li = a.split()#divide by line using
    return len(li)
wordCount('data.txt')

40

In [87]:
# specific word count from the file
# example #1:
# input --This
# output --10
# example #2:
# input --Gitam
# output --1
def specificWordCount(filename,word):
    with open(filename,'r')as f:
        if f.mode=='r':
            a=f.read()
            li=a.split()
    return li.count(word)
specificWordCount('data.txt','This')
            

10

In [99]:
def charCount(filename):
    with open(filename,'r')as f:
        if f.mode == 'r':
            a=f.read()
            li = list(a)
    return len(li)
charCount('data.txt')

222

In [98]:
li=['python programming']
len(li)


1

In [103]:
# find no of lines or rows in the given input stream
def findLineCount(filename,):
    with open(filename,'r') as f:
        if f.mode=='r':
            a=f.read()
            li = a.split('\n')
    return len(li) 
findLineCount('data.txt')

15

In [105]:
def caseCount(filename):
    cntUpper=0
    cntLower=0
    cntDigit=0
    with open(filename,'r') as f:
        if f.mode=='r':
            a=f.read()
            li = list(a)
    for i in range(len(li)):
        if ord(li[i]) >=65 and ord(li[i]) <=90:
            cntUpper+=1
        elif ord(li[i]) >=97 and ord(li[i]) <=122:
            cntLower+=1
        elif ord(li[i]) >=48 and ord(li[i]) <=57:
            cntDigit+=1
    output = 'Upper Case:{0} Lower Case:{1} Digit:{2}'.format(cntUpper,cntLower,cntDigit) 
    return output
caseCount('data.txt')
            

'Upper Case:24 Lower Case:130 Digit:10'

In [13]:
def upperLowerCase( ):
    for i in range(97,123):
        print(chr(i),end=' ')
    print( )
    return
upperLowerCase( )
        

a b c d e f g h i j k l m n o p q r s t u v w x y z 


In [22]:
s=int(input("enter a num:"))
def letterPattern(s):
    n=65
    for i in range(1,s):
        for j in range(1,i+1):
            print(chr(n),end=' ')
        n=n+1
        print(' ')
    return
letterPattern(s)
        

enter a num:12
A  
B B  
C C C  
D D D D  
E E E E E  
F F F F F F  
G G G G G G G  
H H H H H H H H  
I I I I I I I I I  
J J J J J J J J J J  
K K K K K K K K K K K  


In [23]:
class fruits:
    def __init__(self,price):
        self.price=price
obj=fruits(50)
obj.quantity=10
obj.bags=2
print(obj.quantity+len(obj.__dict__))
        
        

13


In [ ]:
n=int(input("enter a num:"))
for i in range(1,n+1):
    for j in range(1,i+1):
        

In [7]:
import numpy as np

A = np.array([[1, 2, 3, 4], [ 4, 5, 6, 7],[7, 8, 9, 1],[1, 2, 3, 4]])
print(A)
def summ( ):
    #i=1
    s=0
    for i in range(5,10):
        print(i,end=' ')
        s=s+i
    return s 
summ()
#i=i+1
#print(s)
    

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 1]
 [1 2 3 4]]
5 6 7 8 9 

35

In [13]:
A[ :4]

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 1],
       [1, 2, 3, 4]])

In [5]:
import numarray
n=numarray.array(range(1,10),shape(4,4))
print(n)

ModuleNotFoundError: No module named 'numarray'

In [33]:
A = np.array([[1, 2, 3, 4], [ 4, 5, 6, 7],[7, 8, 9, 1],[1, 2, 3, 4]])
print(A)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 1]
 [1 2 3 4]]


In [34]:
row,column=A.shape

In [35]:
sum=0
for r in range(0,row):
    for c in range(0,column):
        if (r!=0 and c!=0 and r!=row-1 and c!= column-1):
            sum+=A[r][c]
print(sum)
            

28
